### ISSUE TITLE
Module Import Error on `includes`

### ISSUE THREAD

**Issue by mohammed-amr** [AljazBozic/TransformerFusion#1]
Hello,

Thanks for uploading the eval code!

Line 14 is giving me a module not found on `includes` in `setup.py` Can't find it in the PyPi package index. 

Is this a typo? The script runs and compiles without it.

Thanks.

Edit: just saw your commit, looks like you had removed this module from the repo but not the import in the `setup.py` file.

**Comment by AljazBozic** [comment]
Hi! 

Thanks for letting me know! I removed the includes.py at the last minute, and forgot to remove the dependency in setup.py. Just committed a fix, does it work for you now?

**Comment by mohammed-amr** [comment]
Thanks! Yeah, all good. Closing the issue now.
